name: Build Artifact

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt-get update
            sudo apt-get install -y libtinfo5

      - name: Install Macos dependencies
        if: matrix.os == 'macos-latest'
        run: |
            brew install ncurses
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        if: runner.os != 'Windows'
      
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Upload yamlkt/build
        uses: actions/upload-artifact@v3
        with:
          name: yamlkt-build-${{ matrix.os }}
          path: yamlkt/build
      
      - name: Upload benchmark/build
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-build-${{ matrix.os }}
          path: benchmark/build
      
      - name: Upload buildSrc/build
        uses: actions/upload-artifact@v3
        with:
          name: buildSrc-build-${{ matrix.os }}
          path: buildSrc/build